# Generated by Django 3.0.4 on 2020-03-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome do Herói', models.CharField(blank=True, max_length=100)),
                ('Ranking', models.CharField(blank=True, choices=[('S', '"S" SABICHÃO'), ('A', '"A" ARRETADO'), ('B', '"B" BONZIN'), ('C', '"C" COITADIN')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Vilao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
