# Generated by Django 3.0.4 on 2020-03-20 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_hero_vilao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vilao',
        ),
    ]
